In [1]:
#numpy operations

In [2]:
import numpy as np

In [3]:
arr1=np.random.randint(1,10,(3,4))

In [4]:
arr1

array([[2, 6, 8, 1],
       [1, 2, 4, 3],
       [4, 8, 1, 2]])

In [5]:
arr2=np.random.randint(1,10,(3,4))

In [6]:
arr2

array([[4, 2, 8, 6],
       [7, 4, 4, 2],
       [5, 7, 6, 3]])

In [7]:
arr1+arr2#addition operation

array([[ 6,  8, 16,  7],
       [ 8,  6,  8,  5],
       [ 9, 15,  7,  5]])

In [8]:
arr1*arr2

array([[ 8, 12, 64,  6],
       [ 7,  8, 16,  6],
       [20, 56,  6,  6]])

In [9]:
arr1/arr2# division operation

array([[0.5       , 3.        , 1.        , 0.16666667],
       [0.14285714, 0.5       , 1.        , 1.5       ],
       [0.8       , 1.14285714, 0.16666667, 0.66666667]])

In [10]:
arr1-arr2#substraction operation

array([[-2,  4,  0, -5],
       [-6, -2,  0,  1],
       [-1,  1, -5, -1]])

In [11]:
arr1**arr2

array([[      16,       36, 16777216,        1],
       [       1,       16,      256,        9],
       [    1024,  2097152,        1,        8]])

In [12]:
arr1 & arr2

array([[0, 2, 8, 0],
       [1, 0, 4, 2],
       [4, 0, 0, 2]])

In [13]:
arr1

array([[2, 6, 8, 1],
       [1, 2, 4, 3],
       [4, 8, 1, 2]])

In [14]:
arr2

array([[4, 2, 8, 6],
       [7, 4, 4, 2],
       [5, 7, 6, 3]])

In [15]:
-arr1

array([[-2, -6, -8, -1],
       [-1, -2, -4, -3],
       [-4, -8, -1, -2]])

In [18]:
arr1|arr2

array([[ 6,  6,  8,  7],
       [ 7,  6,  4,  3],
       [ 5, 15,  7,  3]])

In [19]:
#numpy--string function

In [21]:
arr=np.array(["priyanka","nikita"])

In [22]:
np.char.upper(arr)

array(['PRIYANKA', 'NIKITA'], dtype='<U8')

In [23]:
np.char.title(arr)

array(['Priyanka', 'Nikita'], dtype='<U8')

In [24]:
np.char.capitalize(arr)

array(['Priyanka', 'Nikita'], dtype='<U8')

In [25]:
#numpy-Numerical Function

In [26]:
arr1

array([[2, 6, 8, 1],
       [1, 2, 4, 3],
       [4, 8, 1, 2]])

In [28]:
np.sin(arr1)

array([[ 0.90929743, -0.2794155 ,  0.98935825,  0.84147098],
       [ 0.84147098,  0.90929743, -0.7568025 ,  0.14112001],
       [-0.7568025 ,  0.98935825,  0.84147098,  0.90929743]])

In [29]:
np.cos(arr1)

array([[-0.41614684,  0.96017029, -0.14550003,  0.54030231],
       [ 0.54030231, -0.41614684, -0.65364362, -0.9899925 ],
       [-0.65364362, -0.14550003,  0.54030231, -0.41614684]])

In [30]:
np.tanh(arr1)

array([[0.96402758, 0.99998771, 0.99999977, 0.76159416],
       [0.76159416, 0.96402758, 0.9993293 , 0.99505475],
       [0.9993293 , 0.99999977, 0.76159416, 0.96402758]])

In [31]:
np.log10(arr1)

array([[0.30103   , 0.77815125, 0.90308999, 0.        ],
       [0.        , 0.30103   , 0.60205999, 0.47712125],
       [0.60205999, 0.90308999, 0.        , 0.30103   ]])

In [32]:
np.exp(arr1)

array([[7.38905610e+00, 4.03428793e+02, 2.98095799e+03, 2.71828183e+00],
       [2.71828183e+00, 7.38905610e+00, 5.45981500e+01, 2.00855369e+01],
       [5.45981500e+01, 2.98095799e+03, 2.71828183e+00, 7.38905610e+00]])

In [33]:
np.sqrt(arr1)

array([[1.41421356, 2.44948974, 2.82842712, 1.        ],
       [1.        , 1.41421356, 2.        , 1.73205081],
       [2.        , 2.82842712, 1.        , 1.41421356]])

In [34]:
np.power(arr1,2)

array([[ 4, 36, 64,  1],
       [ 1,  4, 16,  9],
       [16, 64,  1,  4]], dtype=int32)

In [35]:
np.mean(arr1)

3.5

In [36]:
np.min(arr1)

1

In [37]:
np.max(arr1)

8

In [38]:
np.median(arr1)

2.5

In [39]:
np.std(arr1)

2.4664414311581235

In [40]:
np.max(arr1)

8