In [1]:
import numpy as np

In [2]:
li = [10,20,30,40,50]

In [3]:
arr = np.array(li)

In [4]:
arr

array([10, 20, 30, 40, 50])

In [5]:
li

[10, 20, 30, 40, 50]

In [6]:
print("dimension", arr.ndim)

dimension 1


In [7]:
print("shape", arr.shape)

shape (5,)


In [8]:
print("data type", arr.dtype)

data type int32


In [9]:
arr1= np.zeros((4,4),int)

In [10]:
arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
arr2= np.ones(5,bool)
arr2

array([ True,  True,  True,  True,  True])

In [12]:
arr3= np.ones((5,5))
arr3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
arr4= np.arange(0,10)

In [14]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr5= np.arange(0,10,2)
arr5

array([0, 2, 4, 6, 8])

In [16]:
arr6= np.arange(10,0,-1)
arr6

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [17]:
arr7= np.arange(10,0,1)
arr7

array([], dtype=int32)

In [18]:
arr8= np.linspace(1,20,5)
arr8

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [19]:
arr9= np.linspace(1,100,10)
arr9

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [20]:
arr10= np.linspace(1,1000,5)
arr10

array([   1.  ,  250.75,  500.5 ,  750.25, 1000.  ])

In [21]:
arr11= np.random.rand(2,4)
arr11

array([[0.94645647, 0.54672519, 0.01555983, 0.3016628 ],
       [0.46900035, 0.10182803, 0.99650863, 0.99466139]])

In [22]:
arr12= np.random.randint(1,10,(3,3))
arr12

array([[6, 9, 1],
       [6, 1, 3],
       [6, 9, 1]])

In [23]:
arr13= np.random.choice([4,5,6,7],(2,2))
arr13

array([[4, 6],
       [6, 7]])

In [24]:
arr14= np.random.randint(10,20,(4))

In [25]:
arr14

array([15, 14, 15, 14])

In [26]:
arr15= np.random.randint(1,10,(4))
arr15

array([6, 1, 4, 6])

In [27]:
arr14+arr15

array([21, 15, 19, 20])