In [1]:
#numpy-sort,search and counting Function

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
arr=np.array([1,2,3,4,4])

In [5]:
arr

array([1, 2, 3, 4, 4])

In [6]:
np.sort(arr)

array([1, 2, 3, 4, 4])

In [9]:
np.searchsorted(arr,34)

5

In [10]:
arr1=np.array([0,8,7,6,5,4,4,0,0,0,0])

In [11]:
arr1

array([0, 8, 7, 6, 5, 4, 4, 0, 0, 0, 0])

In [12]:
np.count_nonzero(arr1)

6

In [14]:
np.where(arr>8)

(array([], dtype=int64),)

In [15]:
np.extract(arr>8,arr)

array([], dtype=int32)

In [16]:
#numpt--byte swapping

In [17]:
arr.byteswap()

array([16777216, 33554432, 50331648, 67108864, 67108864])

In [18]:
#numpy-  copies  & views

In [19]:
arr

array([1, 2, 3, 4, 4])

In [20]:
a=np.copy(arr)

In [21]:
b=arr.view()

In [22]:
b

array([1, 2, 3, 4, 4])

In [23]:
arr

array([1, 2, 3, 4, 4])

In [24]:
b[0]


1

In [26]:
b[4]

4

In [27]:
a

array([1, 2, 3, 4, 4])

In [28]:
import numpy.matlib as nm

In [29]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [30]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [32]:
## numpy--linear algebra 

In [33]:
arr1=np.random.randint([[2,3],[4,5]])

In [34]:
arr2=np.random.randint([[5,3],[2,5]])

In [35]:
np.dot(arr1,arr2)# dot product will come

array([[4, 0],
       [6, 0]])

In [36]:
arr1@arr2

array([[4, 0],
       [6, 0]])

In [38]:
arr1+arr2

array([[3, 2],
       [4, 0]])

In [41]:
arr1**arr2

array([[1, 1],
       [3, 1]])