In [1]:
import numpy as np

In [2]:
arr1= np.random.randint(1,20,(5))
arr1

array([13,  5,  2, 12, 17])

In [3]:
print("sum" , np.sum(arr1))
print("maximum value", np.max(arr1))
print("minimum value", np.min(arr1))
print("standard deviation", np.std(arr1))

sum 49
maximum value 17
minimum value 2
standard deviation 5.491812087098393


In [4]:
arr2= np.random.randint(1,5,(4,4))
arr2

array([[1, 4, 1, 3],
       [3, 4, 2, 2],
       [1, 2, 1, 4],
       [1, 3, 4, 1]])

In [5]:
print("sum y axis", np.sum(arr2, axis=0))

sum y axis [ 6 13  8 10]


In [6]:
print("sum x axis", np.sum(arr2, axis=1))

sum x axis [ 9 11  8  9]


In [7]:
arr3= np.array([1,2,3,4])
arr4= np.array([3,2,3,5])

In [8]:
print(arr3>arr4)
print(arr3==arr4)
print(arr3<=arr4)

[False False False False]
[False  True  True False]
[ True  True  True  True]


In [9]:
arr3>=2

array([False,  True,  True,  True])

In [30]:
arr5= np.random.randint(1,20,(4,4))
arr5

array([[ 2, 13, 15,  7],
       [ 9,  2, 17,  5],
       [14, 19, 12,  7],
       [15, 15,  5,  9]])

In [34]:
arr5[2,3]

7

In [36]:
arr5[0,2]

15

In [42]:
arr5[1:3,0:2]

array([[ 9,  2],
       [14, 19]])