In [5]:
import numpy as np

In [3]:
l=[1,2,3,4]

In [3]:
np.array(l)#one dimensional

array([1, 2, 3, 4])

In [4]:
ar=np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])#two dimensional

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [10]:
a=[1,2,3]

In [11]:
np.asarray(a)

array([1, 2, 3])

In [12]:
b=np.matrix(l)#bydefault matrix is two dimensional

In [13]:
b#matrix is subset of array nd bydefaault matrix is a subclass of array

matrix([[1, 2, 3, 4]])

In [14]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [7]:
a=np.array(l)

In [8]:
a

array([1, 2, 3, 4])

In [9]:
c=a

In [18]:
c

array([1, 2, 3, 4])

In [19]:
c[0]

1

In [20]:
c[0]=100

In [21]:
c

array([100,   2,   3,   4])

In [22]:
a

array([100,   2,   3,   4])

In [23]:
d=np.copy(a)

In [24]:
d

array([100,   2,   3,   4])

In [25]:
a

array([100,   2,   3,   4])

In [26]:
d

array([100,   2,   3,   4])

In [27]:
np.fromfunction(lambda i,j:i==j,(3,3))#i and j is the rows nd columns with the given condition

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [30]:
( i*i for i in range(5))

<generator object <genexpr> at 0x0000021D7A5B1380>

In [31]:
 iterable=( i*i for i in range(5))

In [32]:
np.fromiter(iterable,float)


array([ 0.,  1.,  4.,  9., 16.])

In [33]:
np.fromstring("234 234", sep=' ')#help to asssist terms of froming an array at any given point of the time 

array([234., 234.])

In [34]:
np.fromstring("4, 5", sep=',')

array([4., 5.])

In [35]:
#datatypes in numpy

In [36]:
l=[2,3,4,5,6]


In [37]:
ar=np.array(l)

array([2, 3, 4, 5, 6])

In [38]:
ar

array([1, 2, 3, 4])

In [39]:
ar.ndim#dimensional


1

In [40]:
ar2=np.array([[1,2,3,4],[5,6,7,8]])

In [41]:
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
ar2.ndim#tells the dimension

2

In [43]:
ar.size# tells how many elements are there in an array

4

In [44]:
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
ar2.size

8

In [46]:
ar.shape

(4,)

In [47]:
ar2.shape#means 2 rows and 4 columns

(2, 4)

In [49]:
ar.dtype

dtype('int32')

In [51]:
ar2.dtype


dtype('int32')

In [52]:
ar3=np.array([[1,2,3,4],[5,6,7,8]])

In [53]:
ar3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
ar4=np.array([[1.2,2.3,3.4,4],[5.1,6.2,7.4,8]])

In [55]:
ar4

array([[1.2, 2.3, 3.4, 4. ],
       [5.1, 6.2, 7.4, 8. ]])

In [56]:
ar4.dtype

dtype('float64')

In [57]:
range(5)# strtinf from 0 to 5 except 5

range(0, 5)

In [58]:
list(range(5))# range only take innteger values

[0, 1, 2, 3, 4]

In [60]:
np.arange(2.3,5.6)# 'arange' can take floating values unless rangestart from 2.3 to 5.6

array([2.3, 3.3, 4.3, 5.3])

In [62]:
np.arange(2.3,5.6,.3)#for jump manipulation

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [63]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [64]:
np.linspace(1,5,10)#it will produce 10 data in between 1 to 5 nd divide it with 10 equal space

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [65]:
# ((linspace is genrally a data genrator function))logspace,numpy array functions

In [67]:
np.zeros(5)#one dimensional

array([0., 0., 0., 0., 0.])

In [69]:
np.zeros((3,5))# two dimensional(3 rows and 5 columns)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [70]:
np.zeros((3,4,2))# 3dimensional{ 4X2 means 4 rows and 2 columns}  pronounciate as (we have 4X2 three such kinds of a arrays)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [72]:
np.zeros((3,4,3))


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [73]:
np.zeros((3,4,2,3))# four dimension pronouce as (we have 2X3 four such matrixes)

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [74]:
ar4=np.zeros((3,4,2,3))

In [75]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [76]:
ar4.ndim #dimension but cannot gradually visuales in  4 dimension 

4

In [77]:
np.ones(4)

array([1., 1., 1., 1.])

In [79]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [80]:
np.ones((2,3,2))# 3x2 matrixes completes having 2 dimensional

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [81]:
on=np.ones((2,3,2))# store in a variable

In [82]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [83]:
on*4 # work on any operation

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [85]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [86]:
np.eye(4)#identity matrixes

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [87]:
np.linspace(2,4,20)# gives the data between 2 to 4 

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [88]:
np.logspace(2,5,10)#budefault base =10

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [89]:
np.logspace(2,5,2)#base =2

array([   100., 100000.])

In [94]:
np.random.randn(3,4)# will generate 3x4 data 

array([[-0.40039331, -0.17786851, -0.26517061,  0.25150114],
       [-0.69014783, -2.00983763,  0.9620292 ,  0.04392304],
       [ 1.51425484, -1.17681331,  1.41758304,  1.17192082]])

In [91]:
arr = np.random.randn(4,5)# randn function

In [95]:
import pandas as pd

In [100]:
pd.DataFrame(arr)


NameError: name 'arr' is not defined

In [101]:
np.random.rand(3,4)

array([[0.54649439, 0.41683222, 0.13186486, 0.87080385],
       [0.168952  , 0.14322986, 0.1640618 , 0.64348286],
       [0.48614355, 0.93096375, 0.2429496 , 0.63600065]])

In [102]:
np.random.randint(1,110,(3,4))#(random data from the range 1 to 110 in the formate of 3X4)

array([[98, 86, 73, 47],
       [17, 27, 98, 31],
       [ 5, 51, 44, 19]])

In [103]:
arr=np.random.rand(3,4)

In [104]:
arr

array([[0.6284197 , 0.86190937, 0.1961522 , 0.74110514],
       [0.09016234, 0.53131893, 0.86645002, 0.85558296],
       [0.11191876, 0.05912993, 0.3383951 , 0.57096906]])

In [108]:
arr.reshape(6,2)

array([[0.6284197 , 0.86190937],
       [0.1961522 , 0.74110514],
       [0.09016234, 0.53131893],
       [0.86645002, 0.85558296],
       [0.11191876, 0.05912993],
       [0.3383951 , 0.57096906]])

### 

In [109]:
arr1=arr.reshape(6,2)

In [110]:
arr1

array([[0.6284197 , 0.86190937],
       [0.1961522 , 0.74110514],
       [0.09016234, 0.53131893],
       [0.86645002, 0.85558296],
       [0.11191876, 0.05912993],
       [0.3383951 , 0.57096906]])

In [111]:
arr1[1]# first row

array([0.1961522 , 0.74110514])

In [112]:
arr1[1][1]# 1st row 1 index element

0.7411051447889587

In [113]:
arr1[2]

array([0.09016234, 0.53131893])

In [114]:
arr1[2:5]# data from 2md  to 5th row

array([[0.09016234, 0.53131893],
       [0.86645002, 0.85558296],
       [0.11191876, 0.05912993]])

In [115]:
arr1[2:5,1]#elements from 2nd row to 5th row which has index 1 

array([0.53131893, 0.85558296, 0.05912993])

In [116]:
np.random.randint(1,100,(5,5))

array([[99, 37, 69, 93, 58],
       [73, 64, 27, 29, 99],
       [14, 56, 94, 69, 43],
       [53, 87, 31,  7, 42],
       [34, 11,  7, 95, 64]])

In [117]:
arr=np.random.randint(1,100,(5,5))

In [118]:
arr

array([[48, 88, 23, 79, 36],
       [74, 51, 91, 65, 20],
       [86, 17, 78, 57, 59],
       [91, 22, 12, 69, 81],
       [81, 45, 40, 48, 61]])

In [119]:
arr>5 # will give true will condition matched

array([[False,  True, False,  True, False],
       [ True,  True,  True,  True, False],
       [ True, False,  True,  True,  True],
       [ True, False, False,  True,  True],
       [ True, False, False, False,  True]])

In [120]:
arr[arr>5 ]# will give the data

array([48, 88, 23, 79, 36, 74, 51, 91, 65, 20, 86, 17, 78, 57, 59, 91, 22,
       12, 69, 81, 81, 45, 40, 48, 61])

In [121]:
arr

array([[48, 88, 23, 79, 36],
       [74, 51, 91, 65, 20],
       [86, 17, 78, 57, 59],
       [91, 22, 12, 69, 81],
       [81, 45, 40, 48, 61]])

In [123]:
arr[3:5,[2,3]]# strting from 3 to 5 withcolumns 2 to 3

array([[12, 69],
       [40, 48]])

In [124]:
arr[0][0]

48

In [128]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))



In [129]:
arr1

array([[2, 2, 1],
       [2, 1, 1],
       [1, 1, 1]])

In [130]:
arr2

array([[2, 2, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [131]:
arr1+arr2

array([[4, 4, 2],
       [3, 2, 2],
       [2, 2, 3]])

In [132]:
arr1-arr2

array([[ 0,  0,  0],
       [ 1,  0,  0],
       [ 0,  0, -1]])

In [133]:
arr1*arr2

array([[4, 4, 1],
       [2, 1, 1],
       [1, 1, 2]])

In [134]:
arr1/0

C:\Users\avnis\AppData\Local\Temp\ipykernel_31484\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [135]:
arr1+100

array([[102, 102, 101],
       [102, 101, 101],
       [101, 101, 101]])

In [136]:
arr1**2

array([[4, 4, 1],
       [4, 1, 1],
       [1, 1, 1]])

In [137]:
#numpy-broadcasting

In [138]:
arr=np.zeros((4,4))

In [139]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [140]:
row=np.array([1,2,3,4])

In [141]:
row

array([1, 2, 3, 4])

In [142]:
arr+row # will add row wise which is broadcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [143]:
row.T

array([1, 2, 3, 4])

In [144]:
col=np.array([[1,2,3,4]])

In [145]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [146]:
col

array([[1, 2, 3, 4]])

In [147]:
np.random.randint(1,4,(3,4))

array([[1, 2, 1, 2],
       [1, 1, 3, 2],
       [2, 1, 1, 2]])