In [1]:
import numpy as np

In [2]:
arr= np.array([[3,4],[4,5]])
arr

array([[3, 4],
       [4, 5]])

In [3]:
np.linalg.det(arr)

-1.0

In [4]:
A= np.array([[2,3],[4,5]])
B= np.array([4,6])
X=np.linalg.solve(A,B)


In [5]:
X

array([-1.,  2.])

In [6]:
# eigon values and eigon vectors

In [7]:
arr1= np.array([[1,1],[1,1]])
arr1

array([[1, 1],
       [1, 1]])

In [8]:
x,y= np.linalg.eig(arr1)

In [9]:
x

array([2., 0.])

In [10]:
y

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])