In [1]:
import numpy as np

In [12]:
arr1= np.random.randint(1,10,(4,4))
arr1

array([[9, 7, 7, 6],
       [4, 3, 8, 5],
       [1, 1, 3, 1],
       [6, 6, 1, 7]])

In [19]:
x= arr1.T
x

array([[9, 4, 1, 6],
       [7, 3, 1, 6],
       [7, 8, 3, 1],
       [6, 5, 1, 7]])

In [25]:
np.swapaxes(x,0,1)


array([[9, 7, 7, 6],
       [4, 3, 8, 5],
       [1, 1, 3, 1],
       [6, 6, 1, 7]])

In [43]:
arr2= np.random.randint(1,5,(2,2))
arr2

array([[3, 1],
       [3, 4]])

In [45]:
arr3= np.random.randint(5,10,(2,2))
arr3

array([[7, 6],
       [7, 8]])

In [53]:
conc= np.hstack((arr2,arr3))
conc

array([[3, 1, 7, 6],
       [3, 4, 7, 8]])

In [55]:
arr4= np.random.randint(1,10,(8))
arr4

array([7, 5, 9, 7, 3, 2, 4, 6])

In [57]:
np.split(arr4,2)

[array([7, 5, 9, 7]), array([3, 2, 4, 6])]

In [83]:
arr5= np.random.randint(1,10,(16))
arr5

array([7, 7, 3, 5, 2, 5, 5, 3, 5, 4, 3, 1, 5, 6, 1, 6])

In [91]:
x= arr5.reshape(2,2,2,2)
x

array([[[[7, 7],
         [3, 5]],

        [[2, 5],
         [5, 3]]],


       [[[5, 4],
         [3, 1]],

        [[5, 6],
         [1, 6]]]])

In [93]:
x.reshape(-1)

array([7, 7, 3, 5, 2, 5, 5, 3, 5, 4, 3, 1, 5, 6, 1, 6])