In [1]:
#array manipulation

In [2]:
import numpy as np

In [4]:
arr=np.random.randint(1,10,(3,4))

In [5]:
arr

array([[9, 8, 6, 5],
       [9, 7, 2, 6],
       [1, 4, 6, 8]])

In [6]:
arr.reshape(6,2)

array([[9, 8],
       [6, 5],
       [9, 7],
       [2, 6],
       [1, 4],
       [6, 8]])

In [10]:
arr

array([[9, 8, 6, 5],
       [9, 7, 2, 6],
       [1, 4, 6, 8]])

In [11]:
arr.flatten()

array([9, 8, 6, 5, 9, 7, 2, 6, 1, 4, 6, 8])

In [12]:
arr1=np.array([1,2,3,3,4])

In [13]:
arr1.ndim

1

In [14]:
np.expand_dims(arr1,axis=1)# expand dimension expand one dim into teo dim,axis =1 means columns

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [15]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 3, 4]])

In [16]:
arr

array([[9, 8, 6, 5],
       [9, 7, 2, 6],
       [1, 4, 6, 8]])

In [17]:
np.squeeze(arr)

array([[9, 8, 6, 5],
       [9, 7, 2, 6],
       [1, 4, 6, 8]])

In [18]:
data=np.array([[1],[2],[3]])

In [19]:
data

array([[1],
       [2],
       [3]])

In [20]:
np.squeeze(data)# it will squeeze the single row elements

array([1, 2, 3])

In [22]:
arr1

array([1, 2, 3, 3, 4])

In [23]:
np.repeat(arr1,3)#elements will repeat 3 times 

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [25]:
np.roll(arr1,2)#it will roll/shift the value 2 times ahead

array([3, 4, 1, 2, 3])

In [26]:
arr1

array([1, 2, 3, 3, 4])

In [28]:
np.diag(arr1)# it will shift the elements in the diagonal of arr1

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [9]:
#numpy---binary operation

In [11]:
arr1=np.random.randint(1,10,(3,4))

NameError: name 'np' is not defined